### PR TITLE
Fix #7

### LINKED ISSUE #7: folder-link in config does nothing

### PR DESCRIPTION
**Pull request by PackmanDude**

### CODE REVIEW

**Comment by PackmanDude** [comment]
I will fix spamming issue and will unmark it as draft when ready.

**Comment by nykonhrytsyshyn** [comment]
There is no need to fix this bug, I was going to redo LanguageFile in the next week. Thanks for fixing the link.

**Comment by PackmanDude** [comment]
Whatever, it seems com.minersstudios.mscore.language.LanguageFile is literally the worst written class in the entire codebase (after PlayerInfo). I think you would be able to embed fallback language into plugin directly if you're not that of a 0x developer.

**Comment by PackmanDude** [comment]
> There is no need to fix this bug, I was going to redo LanguageFile in the next week. Thanks for fixing the link.

You should have used gettext and now you're suffering because of your decisions. Happy holidays!

**Pull request merged**
